services:
  mongo:
    image: mongo:latest
    command: ["--bind_ip_all", "--port", "27017", "--auth"]
    volumes:
      - mongo-data:/data/db
    restart: always
    # Port Forwarding to Host for Debugging
    # TODO: Wenn in Produktion: Auskommentieren oder komplett löschen!
    ports:
      - 27017:27017
    networks:
      - ctf-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --port 27017 --quiet --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin
      start_period: 10s
    env_file:
      - .env

  api:
    build:
      context: ./core/backend
      dockerfile: Dockerfile
    restart: always
    networks:
      - ctf-net
    env_file:
      - .env
    # TODO: Healthcheck einfügen -> Konsistent zu Dockerfiles im Core
    # Ohne Healthcheck startet das Scoreboard ohne zu warten
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/ping/"]
#       interval: 30s
#       timeout: 5s
#       start_period: 10s
#       retries: 3
    depends_on:
      mongo:
        condition: service_healthy

  site:
    image: local/site-frontend
    build:
      context: .
      dockerfile: ./core/site/dev.Dockerfile
    restart: always
    networks:
      - ctf-net
    env_file:
      - .env
    volumes:
      - ./core/site/website:/app/website:ro
      - ./custom/assets/:/app/assets/custom:ro
      - ./custom/sites/:/custom/sites:ro
    environment:
      REFLEX_HOT_RELOAD_INCLUDE_PATHS: /custom
#     volumes:
#      - ./core/site/:/app/:ro
#       - ./custom/assets/:/app/assets/
#       - ./custom/sites/:/app/web/sites/
#       - ./custom/tasks/:/app/web/tasks/
#       - ./custom/task_conf.py:/app/web/site_engine/task_conf.py
#     depends_on:
#       # Site wartet aktuell nur auf mongo und nicht zusätzlich auf api
#       mongo:
#         condition: service_healthy
#       # TODO: Warten auf api hinzugefügt
#       api:
#         condition: service_healthy

  scoreboard:
    image: local/scoreboard-frontend
    build:
      context: .
      dockerfile: ./core/scoreboard/Dockerfile
    # TODO: Scoreboard restart:always fehlte hier --> automatischer Neustart bei einem Absturz ist jetzt gegeben!
    restart: always
    networks:
      - ctf-net
    env_file:
      - .env
    volumes:
      - ./custom/assets/:/app/assets/custom:ro
#     depends_on:
#       api:
#         condition: service_healthy

  challenge:
    image: local/challenge-backend
    build:
      context: ./custom/challengebackend
      dockerfile: Dockerfile
    restart: always
    networks:
      - ctf-net
    env_file:
      - .env

  webserver:
    image: caddy:2-alpine
    restart: always
    ports:
      - 443:443
    networks:
      - ctf-net
    depends_on:
      - site
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - ./certs:/etc/ssl/web:ro
      - caddy-site:/data

volumes:
  caddy-site:
  mongo-data:

networks:
  ctf-net:

configs:
  Caddyfile:
    content: |
      ${API_DOMAIN} {
              tls /etc/ssl/web/local.crt /etc/ssl/web/local.key
              encode gzip
              reverse_proxy api:8000
      }

      ${CHALLENGE_DOMAIN} {
              tls /etc/ssl/web/local.crt /etc/ssl/web/local.key
              encode gzip

              reverse_proxy challenge:8000
      }

      ${DOMAIN} {
              tls /etc/ssl/web/local.crt /etc/ssl/web/local.key
              encode gzip

              @backend_routes path /_event /_event/* /ping /_upload /_upload/*
              handle @backend_routes {
                      reverse_proxy site:8000
              }

        handle {
          reverse_proxy site:3000
        }
      }

      ${SCR_DOMAIN} {
              tls /etc/ssl/web/local.crt /etc/ssl/web/local.key
              encode gzip

              @backend_routes path /_event /_event/* /ping /_upload /_upload/*
              handle @backend_routes {
                      reverse_proxy scoreboard:8000
              }

        handle {
          reverse_proxy scoreboard:3000
        }
      }
      


